package ui.playerui;

public enum SiftingOfOth {

	SCORING,
	NUM_OF_REBOUND,
	NUM_OF_ASSIST,
	SCORING_REBOUND_ASSIST,
	NUM_OF_BLOCK_SHOT,
	NUM_OF_STEAL,
	NUM_OF_FOUL,
	NUM_OF_TURN_OVER,
	MINUTE,
	EFFICIENCY,
	NUM_OF_SHOT,
	NUM_OF_THREE_POINT,
	NUM_OF_FREE_THROW,
	DOUBLE_DOUBLE

}
