package entity;

public enum MatchInfo {
	MATCH_ID,
	SEASON,
	DATE_OF_MATCH,
	HOME_COURT_TEAM,
	GUEST_COURT_TEAM,
	TOTAL_SCORE,
	FIRST_SECTION_SCORE,
	SECOND_SECTION_SCORE,
	THIRD_SECTION_SCORE,
	FOURTH_SECTION_SCORE
}
